# Generated by Django 3.1.2 on 2020-10-21 13:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_no', models.IntegerField(primary_key=True, serialize=False)),
                ('budget', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Top10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top10', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_type', models.CharField(choices=[('All Rounder', 'All Rounder'), ('Batsmen', 'Batsmen'), ('Spinners', 'Spin Bowler'), ('Pace Bowler', 'Pace Bowler'), ('WK-Batsman', 'Wicket Keeper')], max_length=15)),
                ('player_rating', models.FloatField()),
                ('price', models.FloatField(default=0, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='api.team')),
            ],
        ),
    ]
