# Generated by Django 3.1.2 on 2020-10-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_type', models.CharField(choices=[('Batsmen', 'Batsmen'), ('Spin Bowler', 'Spin Bowler'), ('Pace Bowler', 'Pace Bowler'), ('Wicket Keeper', 'Wicket Keeper')], max_length=15)),
                ('player_rating', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_no', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
    ]
