# Generated by Django 3.1.2 on 2020-10-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='top10',
            options={
                'managed': False,
            },
        ),
    ]
