# Generated by Django 3.1.2 on 2020-10-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201021_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='top10',
            options={
                'managed': True,
            },
        ),
    ]
