# Generated by Django 3.1.2 on 2020-10-21 07:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201018_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOP10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top10', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=10)),
            ],
        ),
    ]
