# Generated by Django 3.1.2 on 2020-10-21 07:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_top10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top10',
            name='top10',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=10),
        ),
    ]
