# Generated by Django 3.1.2 on 2020-10-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201021_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='captain_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.CharField(choices=[('All Rounder', 'All Rounder'), ('Batsmen', 'Batsmen'), ('Spin Bowler', 'Spin Bowler'), ('Pace Bowler', 'Pace Bowler'), ('Wicket Keeper', 'Wicket Keeper')], max_length=15),
        ),
        migrations.AlterField(
            model_name='player',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
