# Generated by Django 3.1.2 on 2020-10-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201029_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
